"""
Database Models for Stock Trading Advisor
Complete SQLAlchemy models with relationships and utilities
"""

from datetime import datetime
from sqlalchemy import (
    create_engine, Column, Integer, Float, String, 
    DateTime, Boolean, ForeignKey, Text, JSON, Index
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker, Session
from typing import Optional, List
import logging

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

Base = declarative_base()


class Stock(Base):
    """Stock metadata and company information"""
    __tablename__ = 'stocks'
    
    id = Column(Integer, primary_key=True)
    symbol = Column(String(10), unique=True, nullable=False, index=True)
    name = Column(String(255))
    sector = Column(String(100))
    industry = Column(String(100))
    market_cap = Column(Float)
    description = Column(Text)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    prices = relationship('StockPrice', back_populates='stock', cascade='all, delete-orphan')
    indicators = relationship('TechnicalIndicator', back_populates='stock', cascade='all, delete-orphan')
    signals = relationship('Signal', back_populates='stock', cascade='all, delete-orphan')
    trades = relationship('Trade', back_populates='stock', cascade='all, delete-orphan')
    
    def __repr__(self):
        return f"<Stock(symbol='{self.symbol}', name='{self.name}')>"


class StockPrice(Base):
    """Historical and real-time price data"""
    __tablename__ = 'stock_prices'
    __table_args__ = (
        Index('idx_stock_timestamp', 'stock_id', 'timestamp'),
    )
    
    id = Column(Integer, primary_key=True)
    stock_id = Column(Integer, ForeignKey('stocks.id'), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    
    # OHLCV data
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Integer, nullable=False)
    adjusted_close = Column(Float)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    stock = relationship('Stock', back_populates='prices')
    
    def __repr__(self):
        return f"<StockPrice(symbol='{self.stock.symbol}', date='{self.timestamp.date()}', close={self.close})>"


class TechnicalIndicator(Base):
    """Calculated technical indicators for each stock/date"""
    __tablename__ = 'technical_indicators'
    __table_args__ = (
        Index('idx_indicator_stock_timestamp', 'stock_id', 'timestamp'),
    )
    
    id = Column(Integer, primary_key=True)
    stock_id = Column(Integer, ForeignKey('stocks.id'), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    
    # Moving Averages
    sma_20 = Column(Float)
    sma_50 = Column(Float)
    sma_200 = Column(Float)
    ema_12 = Column(Float)
    ema_26 = Column(Float)
    
    # Momentum Indicators
    rsi = Column(Float)
    macd = Column(Float)
    macd_signal = Column(Float)
    macd_histogram = Column(Float)
    
    # Volatility Indicators
    bollinger_upper = Column(Float)
    bollinger_middle = Column(Float)
    bollinger_lower = Column(Float)
    atr = Column(Float)
    
    # Volume Indicators
    volume_sma = Column(Float)
    obv = Column(Float)
    
    # Stochastic
    stoch_k = Column(Float)
    stoch_d = Column(Float)
    
    # Trend Strength
    adx = Column(Float)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    stock = relationship('Stock', back_populates='indicators')
    
    def __repr__(self):
        return f"<TechnicalIndicator(symbol='{self.stock.symbol}', date='{self.timestamp.date()}', rsi={self.rsi})>"


class Signal(Base):
    """Buy/Sell signals generated by the system"""
    __tablename__ = 'signals'
    __table_args__ = (
        Index('idx_signal_stock_date', 'stock_id', 'signal_date'),
    )
    
    id = Column(Integer, primary_key=True)
    stock_id = Column(Integer, ForeignKey('stocks.id'), nullable=False, index=True)
    signal_date = Column(DateTime, nullable=False, index=True)
    signal_type = Column(String(10), nullable=False)  # 'BUY' or 'SELL'
    
    # Signal strength
    confidence = Column(Float, nullable=False)  # 0 to 1
    strength = Column(String(20))  # 'weak', 'moderate', 'strong'
    
    # Price information
    current_price = Column(Float, nullable=False)
    target_price = Column(Float)
    stop_loss_price = Column(Float)
    
    # Reasoning
    primary_reason = Column(String(255))
    technical_score = Column(Float)
    
    # Additional details (JSON)
    details = Column(JSON)
    
    # Status tracking
    is_active = Column(Boolean, default=True)
    is_executed = Column(Boolean, default=False)
    executed_at = Column(DateTime)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    stock = relationship('Stock', back_populates='signals')
    trades = relationship('Trade', back_populates='signal')
    
    def __repr__(self):
        return f"<Signal(symbol='{self.stock.symbol}', type='{self.signal_type}', confidence={self.confidence:.2f})>"


class Trade(Base):
    """Executed trades (paper or live)"""
    __tablename__ = 'trades'
    __table_args__ = (
        Index('idx_trade_stock_date', 'stock_id', 'trade_date'),
    )
    
    id = Column(Integer, primary_key=True)
    stock_id = Column(Integer, ForeignKey('stocks.id'), nullable=False, index=True)
    signal_id = Column(Integer, ForeignKey('signals.id'), index=True)
    
    # Trade details
    trade_type = Column(String(10), nullable=False)  # 'BUY' or 'SELL'
    trade_date = Column(DateTime, nullable=False, index=True)
    shares = Column(Integer, nullable=False)
    price = Column(Float, nullable=False)
    total_value = Column(Float, nullable=False)
    commission = Column(Float, default=0.0)
    
    # Trade mode
    is_paper_trade = Column(Boolean, default=True)
    
    # For SELL trades - track P&L
    entry_price = Column(Float)
    profit_loss = Column(Float)
    profit_loss_percentage = Column(Float)
    
    # Exit reason (for sells)
    exit_reason = Column(String(50))  # 'take_profit', 'stop_loss', 'signal', 'manual'
    
    # Additional details
    notes = Column(Text)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    stock = relationship('Stock', back_populates='trades')
    signal = relationship('Signal', back_populates='trades')
    
    def __repr__(self):
        return f"<Trade(symbol='{self.stock.symbol}', type='{self.trade_type}', shares={self.shares}, price={self.price})>"


class Portfolio(Base):
    """Current portfolio holdings"""
    __tablename__ = 'portfolio'
    
    id = Column(Integer, primary_key=True)
    stock_id = Column(Integer, ForeignKey('stocks.id'), nullable=False, unique=True, index=True)
    
    # Position details
    shares = Column(Integer, nullable=False)
    avg_entry_price = Column(Float, nullable=False)
    current_price = Column(Float)
    total_invested = Column(Float, nullable=False)
    current_value = Column(Float)
    
    # Profit/Loss
    unrealized_profit_loss = Column(Float)
    unrealized_profit_loss_percentage = Column(Float)
    
    # Important dates
    first_purchase_date = Column(DateTime, nullable=False)
    last_update = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Risk management
    stop_loss_price = Column(Float)
    take_profit_price = Column(Float)
    
    def __repr__(self):
        return f"<Portfolio(symbol='{self.stock.symbol}', shares={self.shares}, value=${self.current_value:.2f})>"


class PortfolioHistory(Base):
    """Daily portfolio value tracking"""
    __tablename__ = 'portfolio_history'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, unique=True, index=True)
    
    # Portfolio metrics
    total_value = Column(Float, nullable=False)
    cash_balance = Column(Float, nullable=False)
    invested_value = Column(Float, nullable=False)
    
    # Performance
    daily_return = Column(Float)
    cumulative_return = Column(Float)
    
    # Holdings
    num_positions = Column(Integer, default=0)
    
    # Additional metrics
    sharpe_ratio = Column(Float)
    max_drawdown = Column(Float)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<PortfolioHistory(date='{self.date.date()}', value=${self.total_value:.2f})>"


class BacktestResult(Base):
    """Backtesting results storage"""
    __tablename__ = 'backtest_results'
    
    id = Column(Integer, primary_key=True)
    backtest_name = Column(String(255), nullable=False)
    start_date = Column(DateTime, nullable=False)
    end_date = Column(DateTime, nullable=False)
    
    # Strategy parameters (stored as JSON)
    strategy_params = Column(JSON)
    
    # Results
    initial_capital = Column(Float, nullable=False)
    final_capital = Column(Float, nullable=False)
    total_return = Column(Float)
    annual_return = Column(Float)
    sharpe_ratio = Column(Float)
    max_drawdown = Column(Float)
    
    # Trade statistics
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    win_rate = Column(Float)
    
    # Average trade metrics
    avg_profit = Column(Float)
    avg_loss = Column(Float)
    profit_factor = Column(Float)
    
    # Detailed results (JSON)
    trade_log = Column(JSON)
    equity_curve = Column(JSON)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<BacktestResult(name='{self.backtest_name}', return={self.total_return:.2f}%)>"


class SystemLog(Base):
    """System activity and error logs"""
    __tablename__ = 'system_logs'
    __table_args__ = (
        Index('idx_log_timestamp_level', 'timestamp', 'log_level'),
    )
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    log_level = Column(String(20), nullable=False, index=True)  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    module = Column(String(100))
    function = Column(String(100))
    message = Column(Text, nullable=False)
    details = Column(JSON)
    
    def __repr__(self):
        return f"<SystemLog({self.log_level}: {self.message[:50]})>"


class DatabaseManager:
    """Manages database connections, sessions, and operations"""
    
    def __init__(self, connection_string: str):
        """
        Initialize database manager
        
        Args:
            connection_string: SQLAlchemy connection string
        """
        self.connection_string = connection_string
        self.engine = None
        self.SessionLocal = None
        self._initialize_engine()
    
    def _initialize_engine(self):
        """Initialize SQLAlchemy engine"""
        try:
            # Create engine with proper settings
            if 'sqlite' in self.connection_string:
                # SQLite-specific settings
                self.engine = create_engine(
                    self.connection_string,
                    echo=False,
                    connect_args={'check_same_thread': False}
                )
            else:
                # PostgreSQL/MySQL settings
                self.engine = create_engine(
                    self.connection_string,
                    echo=False,
                    pool_size=5,
                    max_overflow=10,
                    pool_pre_ping=True
                )
            
            self.SessionLocal = sessionmaker(bind=self.engine, autoflush=False, autocommit=False)
            logger.info("✓ Database engine initialized")
        
        except Exception as e:
            logger.error(f"Error initializing database engine: {e}")
            raise
    
    def create_tables(self):
        """Create all tables in the database"""
        try:
            Base.metadata.create_all(self.engine)
            logger.info("✓ Database tables created successfully")
        except Exception as e:
            logger.error(f"Error creating tables: {e}")
            raise
    
    def drop_tables(self):
        """Drop all tables (use with caution!)"""
        try:
            Base.metadata.drop_all(self.engine)
            logger.info("✓ Database tables dropped")
        except Exception as e:
            logger.error(f"Error dropping tables: {e}")
            raise
    
    def get_session(self) -> Session:
        """
        Get a new database session
        
        Returns:
            SQLAlchemy Session object
        """
        return self.SessionLocal()
    
    def close(self):
        """Close database connection"""
        if self.engine:
            self.engine.dispose()
            logger.info("✓ Database connection closed")
    
    # Helper methods for common operations
    
    def add_stock(self, session: Session, symbol: str, name: str = None, 
                  sector: str = None, industry: str = None) -> Stock:
        """
        Add or update a stock in the database
        
        Args:
            session: Database session
            symbol: Stock ticker symbol
            name: Company name
            sector: Industry sector
            industry: Specific industry
        
        Returns:
            Stock object
        """
        try:
            # Check if stock exists
            stock = session.query(Stock).filter_by(symbol=symbol).first()
            
            if stock:
                # Update existing stock
                if name:
                    stock.name = name
                if sector:
                    stock.sector = sector
                if industry:
                    stock.industry = industry
                stock.updated_at = datetime.utcnow()
            else:
                # Create new stock
                stock = Stock(
                    symbol=symbol,
                    name=name or symbol,
                    sector=sector,
                    industry=industry
                )
                session.add(stock)
            
            session.commit()
            logger.debug(f"Stock {symbol} added/updated")
            return stock
        
        except Exception as e:
            session.rollback()
            logger.error(f"Error adding stock {symbol}: {e}")
            raise
    
    def add_signal(self, session: Session, stock_id: int, signal_type: str,
                   confidence: float, current_price: float, **kwargs) -> Signal:
        """
        Add a trading signal to the database
        
        Args:
            session: Database session
            stock_id: Stock ID
            signal_type: 'BUY' or 'SELL'
            confidence: Signal confidence (0-1)
            current_price: Current stock price
            **kwargs: Additional signal parameters
        
        Returns:
            Signal object
        """
        try:
            signal = Signal(
                stock_id=stock_id,
                signal_date=datetime.utcnow(),
                signal_type=signal_type.upper(),
                confidence=confidence,
                current_price=current_price,
                **kwargs
            )
            
            session.add(signal)
            session.commit()
            logger.debug(f"Signal added: {signal_type} for stock_id {stock_id}")
            return signal
        
        except Exception as e:
            session.rollback()
            logger.error(f"Error adding signal: {e}")
            raise
    
    def get_active_signals(self, session: Session, stock_id: Optional[int] = None) -> List[Signal]:
        """
        Get active signals
        
        Args:
            session: Database session
            stock_id: Optional stock ID filter
        
        Returns:
            List of Signal objects
        """
        query = session.query(Signal).filter_by(is_active=True, is_executed=False)
        
        if stock_id:
            query = query.filter_by(stock_id=stock_id)
        
        return query.order_by(Signal.signal_date.desc()).all()
    
    def log_event(self, session: Session, level: str, module: str, 
                  message: str, details: dict = None):
        """
        Log system event to database
        
        Args:
            session: Database session
            level: Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
            module: Module name
            message: Log message
            details: Additional details as dict
        """
        try:
            log = SystemLog(
                log_level=level.upper(),
                module=module,
                message=message,
                details=details
            )
            session.add(log)
            session.commit()
        except Exception as e:
            logger.error(f"Error logging to database: {e}")


# Example usage
if __name__ == "__main__":
    from config import db_config
    
    print("=" * 70)
    print("Database Models - Test")
    print("=" * 70)
    
    # Initialize database
    db = DatabaseManager(db_config.connection_string)
    
    print(f"\n✓ Using: {db_config.connection_string}")
    
    # Create tables
    print("\nCreating tables...")
    db.create_tables()
    
    # Test adding a stock
    print("\nTesting database operations...")
    session = db.get_session()
    
    try:
        # Add test stock
        stock = db.add_stock(session, 'AAPL', 'Apple Inc.', 'Technology', 'Consumer Electronics')
        print(f"✓ Added stock: {stock}")
        
        # Add test signal
        signal = db.add_signal(
            session,
            stock_id=stock.id,
            signal_type='BUY',
            confidence=0.85,
            current_price=175.50,
            target_price=201.83,
            stop_loss_price=166.73,
            primary_reason='RSI oversold, MACD crossover'
        )
        print(f"✓ Added signal: {signal}")
        
        # Get active signals
        signals = db.get_active_signals(session)
        print(f"✓ Active signals: {len(signals)}")
        
        # Log event
        db.log_event(session, 'INFO', 'test', 'Database test completed successfully')
        print("✓ Logged event")
        
    except Exception as e:
        print(f"✗ Error: {e}")
    finally:
        session.close()
        db.close()
    
    print("\n" + "=" * 70)
    print("✓ Database models test complete!")
    print("=" * 70)